services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:8000
        depends_on:
            - web

    db:
        image: postgres:15
        environment:
            POSTGRES_DB: fastapi_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    web:
        build: ./backend
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/fastapi_db
            REDIS_URL: redis://redis:6379/0
            SECRET_KEY: qhhwMXFoZO5Ml8SCipqPgY2RBTILYi6LpP6DDj35BCw
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 30
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - ./backend/app:/app/app
            - ./backend/main.py:/app/main.py

volumes:
    postgres_data:
